### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kskyten** [chadaustin/renaissance#1]
Renaissance is very cool! Could you please add a license? Any additional information would be much  appreciated. Could you explain the code structure? I would like to attempt to generate the AST from Julia. How would I construct the AST directly? How do I then use the AST to generate GLSL code?

**Comment by chadaustin** [comment]
Added MIT license. Use it as you will!

It was a research project mostly to illustrate the idea. I'm not aware of anyone using it for real. So I'd recommend just reading the source or my thesis at https://chadaustin.me/hci_portfolio/thesis.pdf

I'm still interested in the idea, but won't have time to work on it anytime soon.
